from setuptools import setup

setup(
    name='Ticsup',
    version='1',
    author='Alberto Islas',
    author_email='contacto@ticsup.com',
    install_requires=[
        "Django == 1.7.4",
        "conekta==1.1.0",
        "django-all-access==0.7.0",
        "django-appconf==1.0.1",
        "django-autoslug==1.7.2",
        "django-ckeditor==4.4.7",
        "django-encrypted-fields==1.1.1",
        "django-filter==0.8",
        "django-model-utils==2.4",
        "django-notifications-hq==0.6.2",
        "django-postman==3.2.2",
        "djrill==1.3.0",
        "formtags==0.4.1",
        "httplib2==0.9",
        "nose==1.3.4",
        "oauthlib==1.0.3",
        "Pillow==2.7.0",
        "pinax-notifications==2.0.1",
        "pyasn1==0.1.9",
        "pycrypto==2.6.1",
        "python-keyczar==0.715",
        "requests==2.9.1",
        "requests-oauthlib==0.6.0",
        "simplejson==3.6.5",
        "six==1.10.0",
        "Ticsup==1",
        "virtualenv==13.1.2",
        "wheel==0.26.0",
        "django-paypal",
        "reportlab",
        "xhtml2pdf"
    ],
)
